export const pools = [
  {
    id: 'cake-balbt-bnb',
    logo: 'cake/balbt-bnb.svg',
    name: 'bALBT-BNB LP',
    token: 'bALBT-BNB LP',
    tokenDescription: 'Uses: Pancake',
    tokenAddress: '0xa09E3d70dF741961F1974f19AdFeaCb6eCaBaE33',
    tokenDecimals: 18,
    tokenDescriptionUrl: '#',
    earnedToken: 'ballePancakeBALBT-BNB',
    earnedTokenAddress: '0xa09E3d70dF741961F1974f19AdFeaCb6eCaBaE33',
    earnContractAddress: '0xa09E3d70dF741961F1974f19AdFeaCb6eCaBaE33',
    pricePerFullShare: 1,
    tvl: 0,
    oracle: 'pancake-lp',
    oracleId: 'cake-balbt-bnb',
    oraclePrice: 0,
    depositsPaused: false,
    status: 'active',
    platform: 'Pancake',
    assets: ['bALBT', 'BNB'],
    callFee: 0.0,
  },

];
